name: 'CI - Execução Manual'

on:
  workflow_dispatch:

jobs:
  testes:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v4

      - name: Instalar NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'npm'

      - name: Instalar dependências
        run: npm install

      - name: Executar Testes Com Sucesso (trabalho-final.js)
        run: npx mocha ./testes/trabalho-final.js

      - name: Executar Teste Com inconsistência (01-testes.js)
        run: npx mocha ./testes/01-testes.js || echo "Teste com erro concluído - Continuando workflow"
        continue-on-error: true

      